// Reviewed API route shapes only. New/unrecognized routes become /__other__.
// Parameters are position-based, never guessed from the spelling of an identifier.
const ROUTE_TEMPLATES = [
  "/circle-plaza/me/posts/:id/signups/read",
  "/friend/activities/unread-count",
  "/chat/conversations/:id/members/:id/role",
  "/chat/conversations/:id/members/:id/silence",
  "/chat/conversations/:id/messages/:id/readers",
  "/circle-plaza/me/posts/:id/collaboration-recognitions",
  "/circle-plaza/me/posts/:id/signups",
  "/circle-plaza/me/signups/unread-count",
  "/mall/fancy-numbers/custom/purchase",
  "/mall/fancy-numbers/custom/switch",
  "/auth/password/reset",
  "/auth/password/reset-request",
  "/auth/security-code/verify",
  "/avatar-frames/me/equipped",
  "/chat/conversations/:id/avatar",
  "/chat/conversations/:id/burn",
  "/chat/conversations/:id/clear",
  "/chat/conversations/:id/dissolve",
  "/chat/conversations/:id/events",
  "/chat/conversations/:id/leave",
  "/chat/conversations/:id/members",
  "/chat/conversations/:id/members/:id",
  "/chat/conversations/:id/message-days",
  "/chat/conversations/:id/messages",
  "/chat/conversations/:id/mute-all",
  "/chat/conversations/:id/my-alias",
  "/chat/conversations/:id/my-remark",
  "/chat/conversations/:id/name",
  "/chat/conversations/:id/notice",
  "/chat/conversations/:id/owner",
  "/chat/conversations/:id/policies",
  "/chat/conversations/:id/preferences",
  "/chat/conversations/:id/sync",
  "/chat/conversations/circle",
  "/chat/conversations/direct",
  "/chat/conversations/group",
  "/chat/messages/mutations",
  "/chat/messages/search",
  "/circle-invitation/circle/:id/pending",
  "/circle-plaza/posts/:id/report",
  "/circle-plaza/posts/:id/signup",
  "/circle/:id/icon/select",
  "/circle/:id/icon/upload",
  "/friend/activities/:id/read",
  "/friend/requests/:id/accept",
  "/friend/requests/:id/messages",
  "/friend/requests/:id/reject",
  "/friend/tags/:id/friends",
  "/geo/reverse",
  "/geo/search",
  "/group/:id/members/:id/role",
  "/group/:id/members/invite",
  "/mall/fancy-numbers/:id/purchase",
  "/mall/fancy-numbers/:id/switch",
  "/mall/fancy-numbers",
  "/mall/fancy-numbers/availability",
  "/mall/fancy-numbers/me",
  "/mall/fancy-numbers/renew",
  "/note/group/order",
  "/notification/profile/list",
  "/notification/profile/read-all",
  "/notification/push-token/revoke",
  "/qr/tokens/:id/join",
  "/qr/tokens/rotate",
  "/trace/feed/new-count",
  "/user/search/account",
  "/circle-plaza/feed/search",
  "/circle-plaza/me/posts",
  "/auth/change-password",
  "/auth/login",
  "/auth/logout",
  "/auth/logout-all",
  "/auth/logout-others",
  "/auth/me",
  "/auth/register",
  "/auth/security-code",
  "/auth/sessions",
  "/auth/sessions/:id",
  "/auth/single-device-login",
  "/avatar-frames/me",
  "/calls/:id/accept",
  "/calls/:id/cancel",
  "/calls/:id/join-token",
  "/calls/:id/leave",
  "/calls/:id/reject",
  "/calls/current",
  "/calls/direct",
  "/calls/group",
  "/chat/conversations",
  "/circle-invitation/:id/add-verifier",
  "/circle-invitation/:id/admin-approve",
  "/circle-invitation/:id/eligible-verifiers",
  "/circle-invitation/:id/respond",
  "/circle-invitation/invite",
  "/circle-invitation/my-applications",
  "/circle-invitation/pending",
  "/circle-plaza/posts",
  "/circle-plaza/posts/:id",
  "/circle/:id/avatar",
  "/circle/:id/cover",
  "/circle/:id/join",
  "/circle/:id/leave",
  "/coin/gift",
  "/coin/transactions",
  "/coin/wallet",
  "/conversation-groups/:id/members",
  "/friend/:id/remark",
  "/friend/:id/report",
  "/friend/:id/settings",
  "/friend/:id/tags",
  "/friend/:id/tags/:id",
  "/friend/activities",
  "/friend/activities/:id",
  "/friend/block",
  "/friend/block/:id",
  "/friend/blocked",
  "/friend/requests",
  "/friend/requests/:id",
  "/friend/status/:id",
  "/friend/tags",
  "/group-expansions/products",
  "/group-expansions/purchases",
  "/group/:id/leave",
  "/group/:id/members/:id",
  "/group/:id/report",
  "/icon/display",
  "/icon/options",
  "/mall/sections",
  "/membership/plans",
  "/membership/program",
  "/note/:id/chat-media",
  "/note/:id/exports",
  "/note/:id/groups",
  "/note/:id/pin",
  "/note/:id/remark",
  "/note/:id/restore",
  "/note/:id/status",
  "/note/collect",
  "/note/group",
  "/note/group/:id",
  "/note/recycle-bin",
  "/note/share-links",
  "/notification/:id/open-ownership",
  "/notification/:id/read",
  "/notification/circle-push-preference",
  "/notification/push-token",
  "/notification/unread-summary",
  "/privacy/settings",
  "/referrals/me",
  "/qr/tokens",
  "/qr/tokens/:id",
  "/support/config",
  "/temp-chat/:id/end",
  "/temp-chat/mine",
  "/trace/:id/comment",
  "/trace/:id/like",
  "/trace/comment/:id",
  "/upload/presign",
  "/user/appearances",
  "/user/vip-levels",
  "/auth/refresh",
  "/circle/my",
  "/circle-plaza/feed",
  "/notification/list",
  "/notification/read-all",
  "/trace/feed",
  "/circle",
  "/circle-invitation/:id",
  "/circle/:id",
  "/collections",
  "/collections/:id",
  "/conversation-groups",
  "/conversation-groups/:id",
  "/friend",
  "/friend/:id",
  "/note",
  "/note/:id",
  "/notification/:id",
  "/temp-chat",
  "/trace",
  "/trace/:id",
  "/user/:id",
];
const routes = ROUTE_TEMPLATES.map((template) => ({ template, segments: template.split('/') }));

export function safeHttpEndpoint(endpoint: string): string {
  if (!endpoint.startsWith('/') || endpoint.startsWith('//') || endpoint.length > 2048) return '/__other__';
  const pathname = endpoint.split(/[?#]/)[0].replace(/\/$/, '').toLowerCase();
  const segments = pathname.split('/');
  return routes.find((route) => route.segments.length === segments.length &&
    route.segments.every((part, index) => part === ':id' ? segments[index].length > 0 : part === segments[index]))?.template ?? '/__other__';
}

export function safeHttpRequestId(value: unknown): string | undefined {
  return typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value) ? value.toLowerCase() : undefined;
}

export function createHttpRequestId(): string {
  try {
    // Native/web SDK supplies UUIDs without relying on a global crypto polyfill.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const crypto = require('expo-crypto') as { randomUUID?: () => string };
    const uuid = safeHttpRequestId(crypto.randomUUID?.());
    if (uuid) return uuid;
  } catch {
    // Diagnostic correlation is not a credential or an idempotency guarantee.
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (char) => {
    const random = Math.floor(Math.random() * 16);
    return (char === 'x' ? random : (random & 3) | 8).toString(16);
  });
}

export function diagnosticNow(): number {
  return typeof performance !== 'undefined' && typeof performance.now === 'function'
    ? performance.now() : Date.now();
}
