// 由 app/ 的路由文件派生的静态路径段白名单。
//
// 为什么要有这份清单，而不是用「看起来像不像标识符」的正则判断：
// 后端 id 是**不透明**的。MyCirclesScreen 会 router.push(
// `/(tabs)/discover/circle/${encodeURIComponent(id)}`)，一个纯字母的 circle id
// （如 privatecircle）用任何字符类规则都无法与真正的静态段区分开 —— 只要靠猜，
// 就一定会把某类 id 原样发给 Sentry。而 setSentryUserId 是刻意恒 setUser(null)
// 的，从路由名把标识符漏回去等于绕过那个决定。
//
// 所以判定翻转成白名单：**只有出现在真实路由模板里的段才保留**，其余一律 :id。
// 新增路由后必须重新生成，否则那个屏幕的 transaction 会退化成 :id（只丢分组
// 粒度，不会泄漏）—— test/sentry-route-segments.test.js 会扫描 app/ 把漂移钉住。
//
// 重新生成：node scripts/gen-route-segments.mjs
export const STATIC_ROUTE_SEGMENTS: ReadonlySet<string> = new Set([
  '(auth)',
  '(chat)',
  '(onboarding)',
  '(social)',
  '(tabs)',
  'add-friend',
  'admin',
  'app-settings',
  'avatar-frame',
  'avatar-frames',
  'change-password',
  'change-security-code',
  'chat-background',
  'chat-detail',
  'chat-history-date',
  'chat-history-date-results',
  'chat-history-files',
  'chat-history-media',
  'chat-history-search',
  'chat-history-text',
  'chat-info',
  'circle',
  'circles',
  'collections',
  'contacts',
  'create-circle',
  'create-moment',
  'create-post',
  'credit-score',
  'customer-service',
  'decorations',
  'discover',
  'edit',
  'edit-group-notice',
  'fancy-number',
  'filter',
  'find',
  'forgot-password',
  'forward-picker',
  'group-call',
  'group-expansion',
  'groups',
  'guide',
  'icons',
  'invitation',
  'invite',
  'invite-friends',
  'location-picker',
  'login',
  'login-devices',
  'mall',
  'management',
  'member-center',
  'member-rules',
  'messages',
  'moment',
  'moments',
  'new-friends',
  'notes',
  'invite-group-members',
  'new-group',
  'notification-center',
  'notifications',
  'plaza',
  'plaza-post-detail',
  'post-signups',
  'profile',
  'recommend-friend',
  'recycle-bin',
  'register',
  'remark',
  'report-friend',
  'request',
  'scan',
  'search',
  'search-group-members',
  'seats',
  'select-circle',
  'select-city',
  'select-filter-circles',
  'select-note',
  'select-verifier',
  'settings',
  'settings-about',
  'settings-about-privacy-policy',
  'settings-about-product',
  'settings-about-user-agreement',
  'settings-about-version',
  'settings-account-security',
  'settings-appearance',
  'settings-blacklist',
  'settings-notifications',
  'settings-permissions',
  'settings-privacy',
  'settings-storage',
  'settings-storage-usage',
  'share',
  'share-picker',
  'share-post',
  'support-agents',
  'system-announcements',
  'tags',
  'temp-chats',
  'transfer-composer',
  'unlisted',
  'user',
  'verification',
  'verifications',
  'wallet',
]);
