import { StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { useRouter } from 'expo-router';
import { NavHeader } from '@/components/ui/nav-header';
import { Spacing, Typography, useTheme } from '@/theme';

/** Compatibility destination for QR-login links generated by older clients. */
export default function QrLoginDeprecatedScreen() {
  const router = useRouter();
  const { t } = useTranslation();
  const { colors } = useTheme();

  return (
    <View style={[styles.root, { backgroundColor: colors.background }]}>
      <NavHeader
        title={t('qr.loginDeprecatedTitle', { defaultValue: '二维码登录已停用' })}
        onBackPress={() => router.back()}
        fallbackHref="/login"
      />
      <View style={styles.content}>
        <Text style={[styles.title, { color: colors.text }]}>
          {t('qr.loginDeprecatedTitle', { defaultValue: '二维码登录已停用' })}
        </Text>
        <Text style={[styles.message, { color: colors.textSecondary }]}>
          {t('qr.loginDeprecatedMessage', {
            defaultValue: '请在网页端使用账号和密码登录。请重新打开最新版本的登录页面。',
          })}
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  title: { ...Typography.h2, textAlign: 'center' },
  message: {
    ...Typography.body,
    marginTop: Spacing.md,
    maxWidth: 420,
    textAlign: 'center',
  },
});
